### ISSUE TITLE
Zoom/Font size settings?

### ISSUE THREAD

**Issue by pupbrained** [Lakr233/Kimis#10]
As of the current version of Kimis, the UI is quite small on higher-resolution displays which makes text harder to read:

<img width="2120" alt="image" src="https://user-images.githubusercontent.com/33522919/235036223-5604800d-fff7-41af-b58b-420a8dd9cea0.png">

Would it be possible to add a font size option or something similar to mitigate this?

**Comment by Lakr233** [comment]
Kimis does support font size as an option, but it does not have a setting option on UI side. I can show you a way to do this in Terminal.app.

Firstly, you need to get the bundle identifier of your package, it is `as.wiki.qaq.kimis` if you download it from App Store or can be anything if not.
```
➜  ~ mdls -name kMDItemCFBundleIdentifier -r /Applications/Kimis.app 
as.wiki.qaq.kimis
```

Then, processing the following options:

- List Kimis Settings:
```
➜  ~ defaults read as.wiki.qaq.kimis                      
...
    "wiki.qaq.fontSize" = 16;
...
```

- Set Kimis Font Size: (eg: 24 point)
```
➜  ~ defaults write as.wiki.qaq.kimis wiki.qaq.fontSize -int 24
```

- Reset Kimit Font Size to Default:
```
➜  ~ defaults delete as.wiki.qaq.kimis wiki.qaq.fontSize        
```

**Comment by Lakr233** [comment]
The available range for Kimis font size is 8 ... 24 point.

```
    @UserDefault(key: "wiki.qaq.fontSize", defaultValue: 16)
    var defaultNoteFontSize: Int {
        didSet {
            if defaultNoteFontSize < 8 { defaultNoteFontSize = 8 }
            if defaultNoteFontSize > 24 { defaultNoteFontSize = 24 }
        }
    }
```

**Comment by Lakr233** [comment]
<img width="1087" alt="截屏2023-04-28 10 13 50" src="https://user-images.githubusercontent.com/25259084/235037946-40cbf020-3895-479a-b151-3aa2f29cbf19.png">
