### ISSUE TITLE
Hi.

### ISSUE THREAD

**Issue by nauzome** [Lakr233/Kimis#11]
I feel that Kimis is a great app.
In particular, it is epoch-making that it uses a beautiful UI and a native UI.
I thought what I could do. I would like to help you with the translation.
My name is Nauzome ( https://nauzo.me/ ).

**Comment by Lakr233** [comment]
Currently I'm a little busy on something else, I'll get back to you when I'm ready to do the localization. Thanks for help.

**Comment by nauzome** [comment]
I got it.
Please call me anytime.
