### ISSUE TITLE
贴子底部按钮无法正常点击

### ISSUE THREAD

**Issue by Arlia-Etoile** [Lakr233/Kimis#2]
如下图红圈所示，贴子底部的回复、转发、回应、分享按钮点击后无反应，不弹出任何界面。
![79CF3E5D-99FF-4A78-A0F6-0154A71D3E00](https://user-images.githubusercontent.com/70079806/216214534-38fe9ad0-5aaf-4d2a-b9be-8e09bb3a87fd.jpeg)
![39499A27-3433-4303-B909-92F6BF63FD5F](https://user-images.githubusercontent.com/70079806/216214543-4998936c-783e-405d-ac79-2bde60bd42d3.jpeg)

以及，下图红圈中他人回应也无法点击。
![607AC316-E7C4-4391-9A28-5DE155E5D604](https://user-images.githubusercontent.com/70079806/216214943-f0b1e4e2-df88-4e45-ae4c-639214e31899.jpeg)

**Comment by Nekoyue** [comment]
Log 里应该会同时弹 `Unrecognized selector sent to instance` 报错

已知问题，是这段代码在初始化前过早引入 selector 造成的错误，大概这周稍晚些时修复

https://github.com/Lakr233/Kimis/blob/c344f0eb5fbbb3f8462f09c8ec551e5742a20621/Kimis/Interface/Component/NoteView/OperationStack/NoteOperationStrip.swift#L43

**Comment by Nekoyue** [comment]
ce2cb34ec1f0566a86556305e6d2a1b6db891cf4
大概在 1.3 版本修复了 (?)，需要麻烦确认一下

**Comment by Arlia-Etoile** [comment]
现在除了图3区域的都可以正常点击了

**Comment by Arlia-Etoile** [comment]
现在除了图3区域的都可以正常点击了

**Comment by Lakr233** [comment]
> 现在除了图3区域的都可以正常点击了

那个地方本身就不可点。。。。。。。。。。。。。
我没做！

**Comment by Arlia-Etoile** [comment]
那就没有问题了！
