### ISSUE TITLE
Consider lowering retail price

### ISSUE THREAD

**Issue by ThatOneCalculator** [Lakr233/Kimis#5]
While I can understand wanting to make money from your project, $50 is far more than any other Fediverse iOS client -- even Ivory. Maybe making it $5-10 would be more reasonable?

**Comment by oufmilo** [comment]
I totally agree with @ThatOneCalculator 
If it stays at $49 it is to be avoided urgently...

**Comment by Lakr233** [comment]
`While I can understand wanting to make money from your project`

that is not right. I don't want to use this software to make money and I don't want many people to use it. Kimis is a hand-made New Year gift for my friends, not a commodity.

**Comment by Lakr233** [comment]
related https://github.com/Lakr233/Kimis/issues/6#issuecomment-1424589685
