### ISSUE TITLE
Licensing issue

### ISSUE THREAD

**Issue by ThatOneCalculator** [Lakr233/Kimis#6]
You claim that this is an MIT license, which allows free distribution, but then added a non-distribution clause. Is it MIT (allowing free redistribution) or is it not?

**Comment by ThatOneCalculator** [comment]
https://github.com/Lakr233/Kimis/blob/cad3e7ec306e524401628b935ff4291f1ba06e4c/LICENSE#L7-L8 is in direct contradiction with https://github.com/Lakr233/Kimis/blob/main/LICENSE#L15-L16

**Comment by Lakr233** [comment]
I did not claim this is a `MIT License`, I claim it is a `MIT License - Kimis Edition`. I have clarified this in README.md, App Store submission is not allowed. Any other `use, copy, modify, merge, publish, distribute, sublicense, etc...` is allowed.

**Comment by Lakr233** [comment]
Fine, I will remove MIT License and write my own.

**Comment by ThatOneCalculator** [comment]
You might want to consider something like the BSL, but still -- if you claim you just wanted to make this as a gift for friends, why not allow redistribution? Especially if you're telling me to maintain a fork?

**Comment by Lakr233** [comment]
furthermore, in License file: `, subject to the following conditions:` does not contradictory any other statements.

**Comment by Lakr233** [comment]
Redistribution is allowed, but I've had bad things in the past. Some one made a copy of my app, not Kimis, with 0 modification, put it on the app store and make money. I dont want to see things like this happen again.

**Comment by ThatOneCalculator** [comment]
But what if substantial modifications were made to support Calckey? Would you allow a fork to be put on the App Store then?

**Comment by Lakr233** [comment]
I think I can make an exception for you, with some restrictions.

- Make your code open source, or make the modified parts publicly available.
- May compile your code in its entirety using publicly available materials.
- Redistribution allowed in any format but shall not be available in China (including mainland with its affiliated regions such as Taiwan, Hong Kong, etc.)

The above is subject to change and I reserve the right to modify and interpret.

**Comment by Wack0** [comment]
...isn't that third restriction technically unenforceable?

**Comment by Lakr233** [comment]
The main reason doing so is that I live in China. This kind of stuff should be kept carefully. I dont want any trouble. As a trade off, so you can think I've got a dream, I do it in an open source way.

> ...isn't that third restriction technically unenforceable?

Sure, I removed license and copyright noticed requirements because when I publish the source, I understand nothing can be enforced.

> why not Taiwan?
The regulator's jurisdiction over the App Store includes these areas.

**Comment by ThatOneCalculator** [comment]
That's understandable. I will put my fork on Codeberg, and once it is ready, I'll put it on the American/European/Japanese App Store :)
